{{ if not (eq .chezmoi.os "windows") }}
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*/.*", "*/templates", "*/themes"]
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**", "*/.editorconfig"]
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**", "*/.editorconfig"]
[".oh-my-zsh/custom/plugins/fzf-tab"]
    type = "archive"
    url = "https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**"]
[".local/share/oh-my-tmux"]
    type = "archive"
    url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**"]
[".vim/basic.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim"
    refreshPeriod = "168h"
[".vim/pack/plugins/start/gruvbox"]
    type = "archive"
    url = "https://github.com/morhetz/gruvbox/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**"]
[".vim/pack/plugins/opt/chezmoi"]
    type = "archive"
    url = "https://github.com/alker0/chezmoi.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**"]
{{ if .work }}
[".oh-my-zsh/custom/plugins/zsh-aws-vault"]
    type = "archive"
    url = "https://github.com/blimmer/zsh-aws-vault/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**"]
{{ end }}
{{ end -}}
{{ if eq .chezmoi.os "darwin" }}
[".dotfile_extras/terminal_themes/schemes"]
    type = "archive"
    url = "https://github.com/mbadolato/iTerm2-Color-Schemes/releases/latest/download/iterm2-themes.tgz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = ["*.md", ".gitignore", ".github/**"]
{{ end }}
